on: 
  pull_request:
    branches: ["master"]

jobs:
  ci-python:
    name: Python
    uses: ddalpian/workflow-templates/.github/workflows/python-ci-pipeline.yaml@master
    with:
      python-version: 3.12 # Required
      lint-active: true # Optional [Default = true]
      test-active: true # Optional [Default = true]